<?php
require(__DIR__ . '/../libs/PHPMailer-master/class.phpmailer.php');
require_once("DBGetter.php");
require_once("Payment.php");

class MailUtil {
	const ourMail = "rejestracja@maratonykresowe.pl";
	const adminMail = "michal.barej@yahoo.com";
	const ourSite = "http://www.maratonykresowe.pl/mk-system/";

	static function newPassMail($mail, $pass) {
		$message = "<h2>Maratony Kresowe - zmiana hasła</h2>";
		$message .= "<p>Ponieważ wybrałeś opcję, że zapomniałeś hasła, ";
		$message .= "wygenerowaliśmy dla Ciebie nowe hasło.</p>";
		$message .= "<p><strong>Twój login: " . $mail . "</strong></p>";
		$message .= "<p><strong>Twoje nowe hasło: " . $pass . "</strong><p>";
		$message .= "<p>Możesz <a href=\"" . self::ourSite . "\">zalogować się na stronie</a></p>";
		$message .= "<p>Po zalogowaniu, najlepiej zmień hasło.</p>";

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "Maratony Kresowe - nowe hasło";
		$new_mail->Body = $message;
		$new_mail->addAddress($mail);
		$new_mail->isHTML(true);
		$new_mail->send();
		//echo "<p>Wysłano.</p>";	//test
	}

	static function applyOrgMail($options, $cyclist){
		$marathon = DBGetter::getRaceById($options['marathon']);
		$distance = DBGetter::getDistanceName($options['distance']);
		$payment = DBGetter::getPaymentName($options['payment']);

		$message = "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $marathon['place'] . "</h2>";

		ob_start();
		include(__DIR__ . '/../contents/execute_show_cyclist.php'); //sciezka!
		$cyclist_data = ob_get_contents();
		ob_end_clean();

		$message .= $cyclist_data;
		$message .= "<p>Dystans: " . $distance . "</p>";
		$message .= "<p>Sposób płatności: " . $payment . "</p>";
		if ($options['license'] == 'T'){
			$message .= "<p>Zawodnik zaznaczył, że ma licencję PZKol.</p>";
		}
		$message .= "<p>Uwagi: " . wordwrap($options['notes'], 70) . "</p>";
		$message .= "Była to wiadomość automatyczna.</body></html>";

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "MK - zgłoszenie - " . $marathon['place'];
		$new_mail->Body = $message;
		$new_mail->addAddress(self::ourMail);
		$new_mail->isHTML(true);

		$new_mail->send();
	}

	static function applyCyclistMail($options, $cyclist){
		$marathon = DBGetter::getRaceById($options['marathon']);
		$distance = DBGetter::getDistanceName($options['distance']);
		$payment = DBGetter::getPaymentName($options['payment']);

		$message = "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $marathon['place'] . "</h2>";
		$message .= wordwrap("Poniższa wiadomość została wygenerowana automatycznie przez system zgłoszeń Maratonów Kresowych.<br>", 70);
		$message .= "Poniżej dane, które zostały wysłane w Twoim zgłoszeniu.<br><br>";
		$message .= wordwrap("This message was automatically generated by the Maratony Kresowe registration system.<br>", 70);
		$message .= "Below you can find your data which were sent.<br><br>";
		$message .= "<h3>Jeśli to Twój pierwszy start w tym sezonie, w załączniku wysłaliśmy ci formularz. Wydrukuj go, uzupełnij brakujące miejsca i podpisz</h3>";
		$message .= "<h3>If this is your first marathon in this season, we sent you registration form as an attachment. Please print it, fill in the missing spaces and sign.</h3>";

		ob_start();
		include(__DIR__ . '/../contents/execute_show_cyclist.php'); //sciezka!
		$cyclist_data = ob_get_contents();
		ob_end_clean();

		$message .= $cyclist_data;
		$message .= "<p>Dystans: " . $distance . "</p>";
		$message .= "<p>Sposób płatności: " . $payment . "</p>";
		$message .= "<p>Uwagi: " . wordwrap($options['notes'], 70) . "</p>";
		$message .= "<br>";

		ob_start();
		include(__DIR__ . '/../contents/execute_payment.php'); //sciezka!
		$payment_text = ob_get_contents();
		ob_end_clean();

		//$message .= include(__DIR__ . '/../contents/execute_payment.php');
		$message .= wordwrap($payment_text, 70);

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "MK - zgłoszenie - " . $marathon['place'];
		$new_mail->Body = $message;
		$new_mail->addAddress($cyclist->getEmail());
		$new_mail->isHTML(true);

		include(__DIR__ . '/../contents/print_data_to_pdf.php');
		$file_to_attach = __DIR__ . '/../../../mk_dane/zgloszenia/formularz_mk.pdf';
		if (strlen($cyclist->getStartNumber()) == 0){
			$new_mail->addAttachment($file_to_attach);
		}

		$new_mail->send();


	}


	static function errorAccountMail($login){
		$message = "<html> <head></head><body>";
		$message .= "<h2>Maratony Kresowe</h2>";
		$message .= "<p>Błąd z kontem: " . $login . "</p>";

		ob_start();
		
		$message .= "</body></html>";

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "MK - error";
		$new_mail->Body = $message;
		$new_mail->addAddress(self::adminMail);
		$new_mail->isHTML(true);

		$new_mail->send();
	}

	static function applyNoLoginMessage($application_form, &$message){
		$message .= "Imię: " . $application_form['name'] . "<br />";
		$message .= "Nazwisko: " . $application_form['surname'] . "<br />";
		$message .= "Rok urodzenia: " . $application_form['birthyear'] . "<br />";
		$message .= "Numer startowy: " . $application_form['starting_no'] . "<br />";
		$message .= "Kraj: " . $application_form['country'] . "<br />";
		$message .= "Kod pocztowy: " . $application_form['zip_code'] . "<br />";
		$message .= "Miejscowość: " . $application_form['town'] . "<br />";
		$message .= "Drużyna: " . $application_form['team'] . "<br />";
		$message .= "Dystans: " . DBGetter::getDistanceName($application_form['distance']) . "<br />";
		$message .= "Email: " . $application_form['mail'] . "<br />";
		$message .= "Telefon: " . $application_form['phone'] . "<br />";
		$message .= "Sposób płatności: " . DBGetter::getPaymentName($application_form['payment']) . "<br />";
		$message .= "Uwagi: " . wordwrap($application_form['notes'], 70) . "<br />";
	}


	static function applyNoLoginOrgMail($application_form){
		$marathon = DBGetter::getRaceById($application_form['marathon']);

		$message .= "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $marathon['place'] . "</h2>";
		self::applyNoLoginMessage($application_form, $message);
		if ($application_form['license'] == 'T'){
			$message .= "<p>Zawodnik zaznaczył, że ma licencję PZKol.</p>";
		}
		$message .= "Dane dodano do pliku: " . "mk_dane/zgloszenia/" . 
				$marathon['date'] . substr(textWithoutPolishChars($marathon['place']), 0, 3) . 
				".csv <br />";
		$message .= "Była to wiadomość automatyczna.</body></html>";

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "Maratony Kresowe - zgłoszenie - " . $marathon['place'] . ", " .
			$marathon['date'];
		$new_mail->Body = $message;
		$new_mail->addAddress(self::ourMail);
		$new_mail->isHTML(true);

		$new_mail->send();
	}

	static function applyNoLoginCyclistMail($application_form) {
		$marathon = DBGetter::getRaceById($application_form['marathon']);

		$message = "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $marathon['place'] . "</h2>";
		$message .= wordwrap("Poniższa wiadomość została wygenerowana automatycznie przez system zgłoszeń Maratonów Kresowych.<br>", 70);
		$message .= "Poniżej dane, które zostały wysłane w Twoim zgłoszeniu.<br><br>";
		$message .= wordwrap("This message was automatically generated by the Maratony Kresowe registration system.<br>", 70);
		$message .= "Below you can find your data which were sent.<br><br>";
		$message .= "<h3>Jeśli to Twój pierwszy start w tym sezonie, wydrukuj i wypełnij formularz z załącznika.</h3>";
		$message .= "<h3>If this is your first marathon in this season, print and fill in the attached form.</h3>";
		self::applyNoLoginMessage($application_form, $message);

		ob_start();
		include(__DIR__ . '/../contents/execute_payment_no_login.php'); //sciezka!
		$payment_text = ob_get_contents();
		ob_end_clean();
		$message .= wordwrap($payment_text, 70);

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "MK - zgłoszenie - " . $marathon['place'] . ", " . $marathon['date'];
		$new_mail->Body = $message;
		$new_mail->addAddress($application_form['mail']);
		$new_mail->isHTML(true);

		include(__DIR__ . '/../contents/print_data_to_pdf_no_login.php');
		$file_to_attach = __DIR__ . '/../../../mk_dane/zgloszenia/formularz_mk.pdf';
		$new_mail->addAttachment($file_to_attach);

		$new_mail->send();
		//echo "<p>test</p>";
	}


	//////////////////////////

	static function applyCyclocrossMessage($application_form, &$message){
		$message .= "Imię: " . $application_form['name'] . "<br />";
		$message .= "Nazwisko: " . $application_form['surname'] . "<br />";
		$message .= "Płeć:" . $application_form['sex'] . "<br />";
		$message .= "Rok urodzenia: " . $application_form['birthyear'] . "<br />";
		$message .= "Rodzaj licencji: " . $application_form['license_type'] . "<br />";
		$message .= "Kod UCI: " . $application_form['license'] . "<br />";
		$message .= "Kraj: " . $application_form['country'] . "<br />";
		$message .= "Województwo: " . $application_form['province'] . "<br />";
		$message .= "Kod pocztowy: " . $application_form['zip_code'] . "<br />";
		$message .= "Miejscowość: " . $application_form['town'] . "<br />";
		$message .= "Drużyna: " . $application_form['team'] . "<br />";
		$message .= "Email: " . $application_form['mail'] . "<br />";
		$message .= "Uwagi: " . wordwrap($application_form['notes'], 70) . "<br />";
	}


	static function applyCyclocrossOrgMail($application_form){
		$message .= "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $application_form['marathon']['place'] . "</h2>";
		self::applyCyclocrossMessage($application_form, $message);
		$message .= "Dane dodano do pliku: " . "/home/uey6417/mk_dane/zgloszenia/" . 
				$marathon['date'] . substr(textWithoutPolishChars($application_form['marathon']['place']), 0, 3) . 
				".csv <br />";
		$message .= "Była to wiadomość automatyczna.</body></html>";

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "Maratony Kresowe - zgłoszenie - " . $application_form['marathon']['place'] . ", " .
			$marathon['date'];
		$new_mail->Body = $message;
		$new_mail->addAddress(self::ourMail);
		$new_mail->isHTML(true);

		$new_mail->send();
	}

	static function applyCyclocrossCyclistMail($application_form) {
		$message = "<html> <head></head><body>";
		$message .= "<h2>Zgłoszenie na maraton: " . $application_form['marathon']['place'] . "</h2>";
		$message .= wordwrap("Poniższa wiadomość została wygenerowana automatycznie przez system zgłoszeń Maratonów Kresowych.<br>", 70);
		$message .= "Poniżej dane, które zostały wysłane w Twoim zgłoszeniu.<br><br>";
		$message .= wordwrap("This message was automatically generated by the Maratony Kresowe registration system.<br>", 70);
		$message .= "Below you can find your data which were sent.<br><br>";
		$message .= "<h3>Jeśli to Twój pierwszy start w tym sezonie, wydrukuj i wypełnij formularz z załącznika.</h3>";
		$message .= "<h3>If this is your first marathon in this season, print and fill in the attached form.</h3>";
		self::applyCyclocrossMessage($application_form, $message);

		$new_mail = new PHPMailer();
		$new_mail->CharSet = 'UTF-8';
		$new_mail->From = self::ourMail;
		$new_mail->FromName = 'Maratony Kresowe';
		$new_mail->Subject = "MK - zgłoszenie - " . $application_form['marathon']['place'] . ", " . $application_form['marathon']['date'];
		$new_mail->Body = $message;
		$new_mail->addAddress($application_form['mail']);
		$new_mail->isHTML(true);

		include(__DIR__ . '/../contents/print_data_to_pdf_cyclocross.php');
		$file_to_attach = __DIR__ . '/../../../mk_dane/zgloszenia/formularz_mk.pdf';
		$new_mail->addAttachment($file_to_attach);

		$new_mail->send();
		//echo "<p>test</p>";
	}


}

?>